2023-08-29 14:02:52,194 - worker_process - INFO - Worker_process started.
2023-08-29 14:02:52,423 - JsonScanner - ERROR - Traceback (most recent call last):
  File "/home/aienode1/anaconda3/lib/python3.10/site-packages/nvflare/fuel/utils/json_scanner.py", line 98, in _do_scan
    node.processor.process_element(node)
  File "/home/aienode1/anaconda3/lib/python3.10/site-packages/nvflare/private/json_configer.py", line 122, in process_element
    self.process_config_element(self.config_ctx, node)
  File "/home/aienode1/anaconda3/lib/python3.10/site-packages/nvflare/private/fed/client/client_json_config.py", line 74, in process_config_element
    FedJsonConfigurator.process_config_element(self, config_ctx, node)
  File "/home/aienode1/anaconda3/lib/python3.10/site-packages/nvflare/private/fed_json_config.py", line 75, in process_config_element
    c = self.build_component(element)
  File "/home/aienode1/anaconda3/lib/python3.10/site-packages/nvflare/private/fed/client/client_json_config.py", line 106, in build_component
    t = super().build_component(config_dict)
  File "/home/aienode1/anaconda3/lib/python3.10/site-packages/nvflare/fuel/utils/component_builder.py", line 86, in build_component
    return instantiate_class(class_path, class_args)
  File "/home/aienode1/anaconda3/lib/python3.10/site-packages/nvflare/fuel/utils/class_utils.py", line 51, in instantiate_class
    c = get_class(class_path)
  File "/home/aienode1/anaconda3/lib/python3.10/site-packages/nvflare/fuel/utils/class_utils.py", line 30, in get_class
    module_ = importlib.import_module(module_name)
  File "/home/aienode1/anaconda3/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/aienode1/NVFlare/sound_cls/pt/learners/sound_learner.py", line 23, in <module>
    from pt.utils.data_manager import CSVDataManager
  File "/home/aienode1/NVFlare/sound_cls/pt/utils/data_manager.py", line 24
    print('------------------------------', type(glob(os.path.join(self.dir_path, '**/*.wav'), recursive=False))
         ^
SyntaxError: '(' was never closed

2023-08-29 14:02:52,423 - worker_process - ERROR - FL client execution exception: ConfigError: Config error in ['/home/aienode1/NVFlare/sound_cls/mnist-real-world/workspaces/secure_workspace/site-1/startup/../9166945a-d805-44b8-9ab8-63f485708d1a/app_site-1/config/config_fed_client.json']: ConfigError: Error processing ['/home/aienode1/NVFlare/sound_cls/mnist-real-world/workspaces/secure_workspace/site-1/startup/../9166945a-d805-44b8-9ab8-63f485708d1a/app_site-1/config/config_fed_client.json'] in JSON element {'id': 'sound-learner', 'path': 'pt.learners.sound_learner.MNISTLearner', 'args': {'aggregation_epochs': 4, 'lr': 0.01}}: path: components.#1, exception: SyntaxError: '(' was never closed (data_manager.py, line 24)
2023-08-29 14:02:52,423 - FederatedClient - INFO - Shutting down client run: site-1
2023-08-29 14:02:53,196 - MPM - ERROR - main_func execute exception: ConfigError: Config error in ['/home/aienode1/NVFlare/sound_cls/mnist-real-world/workspaces/secure_workspace/site-1/startup/../9166945a-d805-44b8-9ab8-63f485708d1a/app_site-1/config/config_fed_client.json']: ConfigError: Error processing ['/home/aienode1/NVFlare/sound_cls/mnist-real-world/workspaces/secure_workspace/site-1/startup/../9166945a-d805-44b8-9ab8-63f485708d1a/app_site-1/config/config_fed_client.json'] in JSON element {'id': 'sound-learner', 'path': 'pt.learners.sound_learner.MNISTLearner', 'args': {'aggregation_epochs': 4, 'lr': 0.01}}: path: components.#1, exception: SyntaxError: '(' was never closed (data_manager.py, line 24)
2023-08-29 14:02:53,198 - MPM - ERROR - Traceback (most recent call last):
  File "/home/aienode1/anaconda3/lib/python3.10/site-packages/nvflare/fuel/utils/json_scanner.py", line 98, in _do_scan
    node.processor.process_element(node)
  File "/home/aienode1/anaconda3/lib/python3.10/site-packages/nvflare/private/json_configer.py", line 122, in process_element
    self.process_config_element(self.config_ctx, node)
  File "/home/aienode1/anaconda3/lib/python3.10/site-packages/nvflare/private/fed/client/client_json_config.py", line 74, in process_config_element
    FedJsonConfigurator.process_config_element(self, config_ctx, node)
  File "/home/aienode1/anaconda3/lib/python3.10/site-packages/nvflare/private/fed_json_config.py", line 75, in process_config_element
    c = self.build_component(element)
  File "/home/aienode1/anaconda3/lib/python3.10/site-packages/nvflare/private/fed/client/client_json_config.py", line 106, in build_component
    t = super().build_component(config_dict)
  File "/home/aienode1/anaconda3/lib/python3.10/site-packages/nvflare/fuel/utils/component_builder.py", line 86, in build_component
    return instantiate_class(class_path, class_args)
  File "/home/aienode1/anaconda3/lib/python3.10/site-packages/nvflare/fuel/utils/class_utils.py", line 51, in instantiate_class
    c = get_class(class_path)
  File "/home/aienode1/anaconda3/lib/python3.10/site-packages/nvflare/fuel/utils/class_utils.py", line 30, in get_class
    module_ = importlib.import_module(module_name)
  File "/home/aienode1/anaconda3/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/aienode1/NVFlare/sound_cls/pt/learners/sound_learner.py", line 23, in <module>
    from pt.utils.data_manager import CSVDataManager
  File "/home/aienode1/NVFlare/sound_cls/pt/utils/data_manager.py", line 24
    print('------------------------------', type(glob(os.path.join(self.dir_path, '**/*.wav'), recursive=False))
         ^
SyntaxError: '(' was never closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aienode1/anaconda3/lib/python3.10/site-packages/nvflare/private/json_configer.py", line 114, in configure
    self._do_configure()
  File "/home/aienode1/anaconda3/lib/python3.10/site-packages/nvflare/private/json_configer.py", line 107, in _do_configure
    self.json_scanner.scan(self)
  File "/home/aienode1/anaconda3/lib/python3.10/site-packages/nvflare/fuel/utils/json_scanner.py", line 148, in scan
    self._do_scan(node)
  File "/home/aienode1/anaconda3/lib/python3.10/site-packages/nvflare/fuel/utils/json_scanner.py", line 121, in _do_scan
    self._do_scan(_child_node(node, k, 0, v))
  File "/home/aienode1/anaconda3/lib/python3.10/site-packages/nvflare/fuel/utils/json_scanner.py", line 124, in _do_scan
    self._do_scan(_child_node(node, node.key, i + 1, element[i]))
  File "/home/aienode1/anaconda3/lib/python3.10/site-packages/nvflare/fuel/utils/json_scanner.py", line 103, in _do_scan
    raise ConfigError(
nvflare.fuel.common.excepts.ConfigError: Error processing ['/home/aienode1/NVFlare/sound_cls/mnist-real-world/workspaces/secure_workspace/site-1/startup/../9166945a-d805-44b8-9ab8-63f485708d1a/app_site-1/config/config_fed_client.json'] in JSON element {'id': 'sound-learner', 'path': 'pt.learners.sound_learner.MNISTLearner', 'args': {'aggregation_epochs': 4, 'lr': 0.01}}: path: components.#1, exception: SyntaxError: '(' was never closed (data_manager.py, line 24)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aienode1/anaconda3/lib/python3.10/site-packages/nvflare/fuel/f3/mpm.py", line 144, in run
    rc = main_func()
  File "/home/aienode1/anaconda3/lib/python3.10/site-packages/nvflare/private/fed/app/client/worker_process.py", line 141, in main
    raise e
  File "/home/aienode1/anaconda3/lib/python3.10/site-packages/nvflare/private/fed/app/client/worker_process.py", line 136, in main
    client_app_runner.start_run(app_root, args, config_folder, federated_client, secure_train, sp)
  File "/home/aienode1/anaconda3/lib/python3.10/site-packages/nvflare/private/fed/client/client_app_runner.py", line 42, in start_run
    self.client_runner = self.create_client_runner(app_root, args, config_folder, federated_client, secure_train)
  File "/home/aienode1/anaconda3/lib/python3.10/site-packages/nvflare/private/fed/client/client_app_runner.py", line 61, in create_client_runner
    conf.configure()
  File "/home/aienode1/anaconda3/lib/python3.10/site-packages/nvflare/private/json_configer.py", line 116, in configure
    raise ConfigError("Config error in {}: {}".format(self.config_file_name, secure_format_exception(e)))
nvflare.fuel.common.excepts.ConfigError: Config error in ['/home/aienode1/NVFlare/sound_cls/mnist-real-world/workspaces/secure_workspace/site-1/startup/../9166945a-d805-44b8-9ab8-63f485708d1a/app_site-1/config/config_fed_client.json']: ConfigError: Error processing ['/home/aienode1/NVFlare/sound_cls/mnist-real-world/workspaces/secure_workspace/site-1/startup/../9166945a-d805-44b8-9ab8-63f485708d1a/app_site-1/config/config_fed_client.json'] in JSON element {'id': 'sound-learner', 'path': 'pt.learners.sound_learner.MNISTLearner', 'args': {'aggregation_epochs': 4, 'lr': 0.01}}: path: components.#1, exception: SyntaxError: '(' was never closed (data_manager.py, line 24)

2023-08-29 14:02:53,199 - MPM - INFO - MPM: Good Bye!
